### PR TITLE
Update MKW_Installation_Guide_EN.txt

### PR DESCRIPTION
**Pull request by rpdistiso**
I edited the installation guide.

### CODE REVIEW

**Comment by Midou36O** [comment]
You're supposed to use the installer rather than manually do it (this was required during v0.2.0 but no longer is)

**Comment by rpdistiso** [comment]
I used the .txt from the archive

**Comment by Midou36O** [comment]
Huh, i'm sure that i fixed the installer 🤔 So manually installing isn't needed anymore. Let me know if that's not the case.

**Comment by rpdistiso** [comment]
I haven't updated to v0.2.0 yet but, when I tried loading MKW3DS in Citra a window loaded stating, "No MKW3DS files detected"

**Comment by Midou36O** [comment]
Ah yes, i haven't added support for citra yet. Join the upcoming mario kart wii 3ds discord server to get the new plugins. I should be able to repackage the installation files in a .zip format for ease of use :p

**Comment by rpdistiso** [comment]
I already am I'm Ray D#1994

**Comment by rpdistiso** [comment]
I cannot access discord currently, can you send the updated plugin file, please?

**Comment by CyberYoshi64** [comment]
This guide you gave is not plausible. The folder structure is different; basically identical to CTGP-7. I already plan on expanding the CTGP-7 PC installer to do this mod, as well as updating the MKW3DS Launcher to download the files from this repository for installation.

**Comment by CyberYoshi64** [comment]
> I cannot access discord currently, can you send the updated plugin file, please?

I have left a compiled plugin in the plugin's repo [here](https://github.com/MKW3DS/MKW3DSPlugin/blob/main/mkw3ds.3gx).

**Pull request closed without merging**
